<?php

/**
 * @file
 * Declares Views API version. And adds CSS.
 */

/**
 * Implementation of hook_views_api().
 */
function freepager_views_api() {
  return array(
    'api' => '3.0',
  );
}

/**
 * Implementation of hook_init().
 */
function freepager_init() {
  $path = drupal_get_path('module', 'freepager') .'/freepager.css';
  drupal_add_css($path, 'module', 'all', FALSE);
}

function freepager_preprocess_views_freepager(&$vars) {
  $view = &$vars['view'];
  $fields = array('path', 'previous', 'current', 'next');
  
  foreach($fields as $field) {
    $field_names[$field] = $vars['view']->display_handler->options[$field];
  }

  $current_path = implode('/', arg());

  foreach ($view->result as $key => $row) {
    $rendered_path = $view->render_field($field_names['path'], $key);
    if ($rendered_path == $current_path) {
      $vars['previous'] = $view->render_field($field_names['previous'], $key - 1);
      $vars['previous_path'] = $view->render_field($field_names['path'], $key - 1);
      $vars['current'] = $view->render_field($field_names['current'], $key);
      $vars['current_path'] = $view->render_field($field_names['path'], $key);
      $vars['next'] = $view->render_field($field_names['next'], $key + 1);
      $vars['next_path'] = $view->render_field($field_names['path'], $key + 1);
      $vars['row_number'] = $key;
    }
  }
}
