<?php

/**
 * @file
 * Declares Views API version. And adds CSS.
 */

/**
 * Implementation of hook_views_api().
 */
function freepager_views_api() {
  return array(
    'api' => '3.0',
  );
}

/**
 * Implementation of hook_init().
 */
function freepager_init() {
  $path = drupal_get_path('module', 'freepager') .'/freepager.css';
  drupal_add_css($path, 'module', 'all', FALSE);
}

function freepager_preprocess_views_freepager(&$vars) {
  $fields = array('path', 'previous', 'current', 'next');
  
  foreach($fields as $field) {
    $field_names[$field] = $vars['view']->display_handler->options[$field];
  }
  dpm($vars['view']->result);
}
